import {
  Activity,
  Archive,
  BookOpen,
  Boxes,
  Bug,
  ClipboardCheck,
  Cog,
  FileClock,
  FolderCog,
  Gauge,
  Globe,
  Hammer,
  HardDriveDownload,
  HeartPulse,
  Library,
  ListRestart,
  ShieldCheck,
  type LucideIcon,
} from 'lucide-react'

export type RouteStatus = 'stub' | 'in-progress' | 'complete'
export type RouteGroup = 'Command' | 'Operations' | 'Tools' | 'System'

export interface RouteConfig {
  path: string
  label: string
  description: string
  sourceView: string
  sourceViewModel: string
  status: RouteStatus
  group: RouteGroup
  icon: LucideIcon
}

export const routes: RouteConfig[] = [
  {
    path: '/',
    label: 'Dashboard',
    description: 'Component health and environment status',
    sourceView: 'DashboardView',
    sourceViewModel: 'DashboardViewModel',
    status: 'in-progress',
    group: 'Command',
    icon: Gauge,
  },
  {
    path: '/install',
    label: 'Install',
    description: 'Queue and track archive or folder installs',
    sourceView: 'InstallView',
    sourceViewModel: 'InstallViewModel',
    status: 'in-progress',
    group: 'Command',
    icon: HardDriveDownload,
  },
  {
    path: '/library',
    label: 'Library',
    description: 'Review, filter, and manage installed mods',
    sourceView: 'LibraryView',
    sourceViewModel: 'LibraryViewModel',
    status: 'in-progress',
    group: 'Command',
    icon: Library,
  },
  {
    path: '/browse',
    label: 'Browse',
    description: 'Browse LSPDFR sources and queue downloads',
    sourceView: 'BrowseView',
    sourceViewModel: 'BrowseViewModel',
    status: 'stub',
    group: 'Command',
    icon: Globe,
  },
  {
    path: '/backups',
    label: 'Backups',
    description: 'Manage restore points and backup policy',
    sourceView: 'BackupsView',
    sourceViewModel: 'BackupsViewModel',
    status: 'stub',
    group: 'Operations',
    icon: Archive,
  },
  {
    path: '/config',
    label: 'Config',
    description: 'Inspect and edit mod configuration files',
    sourceView: 'ConfigView',
    sourceViewModel: 'ConfigViewModel',
    status: 'stub',
    group: 'Operations',
    icon: FolderCog,
  },
  {
    path: '/diagnostics',
    label: 'Diagnostics',
    description: 'Scan plugin health, dependencies, and crashes',
    sourceView: 'DiagnosticsView',
    sourceViewModel: 'DiagnosticsViewModel',
    status: 'stub',
    group: 'Operations',
    icon: Activity,
  },
  {
    path: '/history',
    label: 'History',
    description: 'Audit installs, changes, and file operations',
    sourceView: 'HistoryView',
    sourceViewModel: 'HistoryViewModel',
    status: 'in-progress',
    group: 'Operations',
    icon: FileClock,
  },
  {
    path: '/profiles',
    label: 'Profiles',
    description: 'Switch loadouts and profile state',
    sourceView: 'ProfilesView',
    sourceViewModel: 'ProfilesViewModel',
    status: 'stub',
    group: 'Operations',
    icon: Boxes,
  },
  {
    path: '/settings',
    label: 'Settings',
    description: 'Configure paths, backups, install behavior, and APIs',
    sourceView: 'SettingsView',
    sourceViewModel: 'SettingsViewModel',
    status: 'in-progress',
    group: 'System',
    icon: Cog,
  },
  {
    path: '/logs',
    label: 'Log Viewer',
    description: 'Read recent app and game logs',
    sourceView: 'LogViewerView',
    sourceViewModel: 'LogViewerViewModel',
    status: 'in-progress',
    group: 'System',
    icon: BookOpen,
  },
  {
    path: '/safe-mode',
    label: 'Safe Mode',
    description: 'Prepare a low-risk launch state',
    sourceView: 'SafeModeView',
    sourceViewModel: 'SafeModeViewModel',
    status: 'stub',
    group: 'Tools',
    icon: ShieldCheck,
  },
  {
    path: '/dev-diagnostics',
    label: 'Dev Diagnostics',
    description: 'Inspect feature flags and developer diagnostics',
    sourceView: 'DevDiagnosticsView',
    sourceViewModel: 'DevDiagnosticsViewModel',
    status: 'stub',
    group: 'System',
    icon: Bug,
  },
  {
    path: '/oiv',
    label: 'OIV Creator',
    description: 'Build or inspect OpenIV packages',
    sourceView: 'OivView',
    sourceViewModel: 'OivViewModel',
    status: 'stub',
    group: 'Tools',
    icon: Hammer,
  },
  {
    path: '/cleanup',
    label: 'Cleanup',
    description: 'Find removable files and apply guarded cleanup',
    sourceView: 'CleanupView',
    sourceViewModel: 'CleanupViewModel',
    status: 'in-progress',
    group: 'Tools',
    icon: ListRestart,
  },
  {
    path: '/patrol-readiness',
    label: 'Patrol Readiness',
    description: 'Validate the install before launching a session',
    sourceView: 'PatrolReadinessDashboardView',
    sourceViewModel: 'PatrolReadinessDashboardViewModel',
    status: 'in-progress',
    group: 'Command',
    icon: ClipboardCheck,
  },
  {
    path: '/setup',
    label: 'Setup Wizard',
    description: 'Initial GTA V path and environment setup',
    sourceView: 'SetupWizardView',
    sourceViewModel: 'SetupWizardViewModel',
    status: 'stub',
    group: 'System',
    icon: HeartPulse,
  },
]
