using System.Collections.Generic;
using System.Text.RegularExpressions;
using LSPDFRManager.Features.OivCreatorTemplates.Models;

namespace LSPDFRManager.Features.OivCreatorTemplates;

public sealed class OivTemplateController : IOivTemplateController
{
    public IReadOnlyList<OivTemplateDefinition> GetAvailableTemplates() => new List<OivTemplateDefinition>
    {
        new(OivTemplateId.LspdfrPlugin, "LSPDFR Plugin", "Templates for DLL and INI files."),
        new(OivTemplateId.DlcPack, "DLC Pack", "Standard folder structure for Add-on DLCs."),
        new(OivTemplateId.VehicleReplace, "Vehicle Replace", "Replaces standard vehicles in patchday folders.")
    };

    public OivTemplateApplyPlan BuildPlan(OivTemplateId id, OivWizardSnapshot snapshot)
    {
        var metadata = new Dictionary<string, string>();
        var paths = new List<PathRule>();

        switch (id)
        {
            case OivTemplateId.LspdfrPlugin:
                metadata["Description"] = "LSPDFR Plugin package generated by LSPDFR Manager.";
                paths.Add(new PathRule(".dll", "plugins/LSPDFR/", false));
                paths.Add(new PathRule(".ini", "plugins/LSPDFR/", false));
                break;

            case OivTemplateId.DlcPack:
                metadata["Version"] = "1.0.0";
                // Suggest dlcpacks/[name]/dlc.rpf if a dlc.rpf is present or added.
                paths.Add(new PathRule("dlc.rpf", $"dlcpacks/{Sanitize(snapshot.PackageName)}/dlc.rpf"));
                break;

            case OivTemplateId.VehicleReplace:
                metadata["Description"] = "Vehicle replacement mod.";
                paths.Add(new PathRule(".yft", "mods/update/x64/dlcpacks/patchday22ng/dlc.rpf/x64/levels/gta5/vehicles.rpf/", false));
                paths.Add(new PathRule(".ytd", "mods/update/x64/dlcpacks/patchday22ng/dlc.rpf/x64/levels/gta5/vehicles.rpf/", false));
                paths.Add(new PathRule("vehicles.meta", "mods/update/x64/dlcpacks/patchday22ng/dlc.rpf/common/data/levels/gta5/"));
                break;
        }

        return new OivTemplateApplyPlan(metadata, paths);
    }

    private static readonly Regex _unsafeChars = new(@"[^a-z0-9_\-]", RegexOptions.Compiled);
    private static readonly Regex _repeatedUnderscores = new(@"_+", RegexOptions.Compiled);

    private static string Sanitize(string name)
    {
        if (string.IsNullOrWhiteSpace(name)) return "my_mod";
        var safe = _unsafeChars.Replace(name.ToLowerInvariant(), "_");
        safe = _repeatedUnderscores.Replace(safe, "_").Trim('_');
        return string.IsNullOrEmpty(safe) ? "my_mod" : safe;
    }
}
